# -*- coding: utf-8 -*-
"""Decision_Boundary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VlwPHV_dEQCP6uADonIMu5OI0gmJH9pY
"""

def plot_decision_boundary(X, y, model):
    x_min, x_max = X[:, 0].min() - 0.1, X[:, 0].max() + 0.1
    y_min, y_max = X[:, 1].min() - 0.1, X[:, 1].max() + 0.1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, 0.01), np.arange(y_min, y_max, 0.01))
    Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)

    plt.contourf(xx, yy, Z, alpha=0.3)
    plt.scatter(X[:, 0], X[:, 1], c=y, edgecolor='k', s=50)
    plt.xlabel("Body Mass ")
    plt.ylabel("Beak Length ")
    plt.title("Perceptron Decision Boundary")
    plt.show()


plot_decision_boundary(X, y, perceptron)